schema_version: 20180708
name: myfunc
version: 0.0.45
runtime: java
cmd: com.example.fn.HelloFunction::handleRequest
timeout: 60
idle_timeout: 60
config:
  funcKey1: funcValue1
  funcKey2: funcValue2
triggers:
- name: endpoint
  type: http
  source: /mount
- name: endpointv2
  type: http
  source: /v2/mount
- name: trigger3
  type: http
  source: /v3/mount
