schema_version: 20180708
name: myfunc
version: 0.0.42
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk17-1.0.165
run_image: fnproject/fn-java-fdk:jre17-1.0.165
cmd: com.example.fn.HelloFunction::handleRequest
timeout: 60
idle_timeout: 60
config:
  funcKey1: funcValue1
  funcKey2: funcValue2
triggers:
- name: endpoint
  type: http
  source: /mount
- name: endpointv2
  type: http
  source: /v2/mount
- name: trigger3
  type: http
  source: /v3/mount
