schema_version: 20180708
name: ontology
version: 0.0.32
runtime: java11
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.124
run_image: fnproject/fn-java-fdk:jre11-1.0.124
cmd: com.minsait.onesait.OntologyCalculationFn::handleRequest
config:
  API_KEY: d4d173323edb49cb8df923182863fda5
  GRAYLOG_HOST: log-centralizer
  GRAYLOG_PORT: "12201"
  BACKEND_SERVER: https://development.onesaitplatform.com/
triggers:
- name: endpoint
  type: http
  source: /calculate
